import { Resource, DemandPost } from "./types";

export const CURRENT_USER = {
  name: "Ramesh Chaudhary",
  village: "Kishangarh",
  district: "Ajmer",
  state: "Rajasthan",
};

export const resources: Resource[] = [
  {
    id: "m-1001",
    category: "machinery",
    type: "Tractor",
    title: "Mahindra 575 DI Tractor, 47 HP",
    description:
      "Well-maintained 47 HP tractor available for ploughing, tilling and trolley haulage. Comes with a trained operator on request.",
    ownerName: "Suresh Patel",
    ownerVillageYears: 14,
    location: { village: "Bhinay", district: "Ajmer", state: "Rajasthan", distanceKm: 6.2 },
    price: 650,
    priceUnit: "per hour",
    availability: { status: "available", detail: "Free now, all week" },
    condition: "2019 model, serviced every season",
    icon: "🚜",
    listedDaysAgo: 2,
    rating: 4.7,
    ratingCount: 23,
    contactPhone: "9829•••••41",
    tags: ["ploughing", "haulage", "operator available"],
  },
  {
    id: "m-1002",
    category: "machinery",
    type: "Rotavator",
    title: "6-Feet Rotavator for Field Prep",
    description:
      "Fieldking rotavator, ideal for seedbed preparation before sowing wheat or mustard. Pairs with any 35+ HP tractor.",
    ownerName: "Ismail Khan",
    ownerVillageYears: 9,
    location: { village: "Pushkar", district: "Ajmer", state: "Rajasthan", distanceKm: 11.8 },
    price: 900,
    priceUnit: "per acre",
    availability: { status: "upcoming", detail: "Free after 20 Aug" },
    condition: "Blades replaced this season",
    icon: "⚙️",
    listedDaysAgo: 5,
    rating: 4.4,
    ratingCount: 12,
    contactPhone: "9414•••••08",
    tags: ["seedbed prep", "rabi season"],
  },
  {
    id: "m-1003",
    category: "machinery",
    type: "Combine Harvester",
    title: "New Holland Combine Harvester",
    description:
      "High-capacity combine harvester for wheat and mustard. Covers 4-5 acres a day, grain tank included.",
    ownerName: "Vikram Singh Shekhawat",
    ownerVillageYears: 20,
    location: { village: "Nasirabad", district: "Ajmer", state: "Rajasthan", distanceKm: 18.4 },
    price: 2400,
    priceUnit: "per acre",
    availability: { status: "booked", detail: "Booked till 24 Aug" },
    condition: "2021 model, low engine hours",
    icon: "🌾",
    listedDaysAgo: 1,
    rating: 4.9,
    ratingCount: 31,
    contactPhone: "9982•••••17",
    tags: ["harvesting", "wheat", "mustard"],
  },
  {
    id: "m-1004",
    category: "machinery",
    type: "Seed Drill",
    title: "9-Tyne Seed-cum-Fertilizer Drill",
    description:
      "Precision seed drill for even sowing of wheat, gram and mustard with simultaneous fertilizer placement.",
    ownerName: "Govind Ram Jat",
    ownerVillageYears: 11,
    location: { village: "Kekri", district: "Ajmer", state: "Rajasthan", distanceKm: 27.5 },
    price: 500,
    priceUnit: "per acre",
    availability: { status: "available", detail: "Free now" },
    condition: "Good condition, calibrated",
    icon: "🌱",
    listedDaysAgo: 4,
    rating: 4.3,
    ratingCount: 8,
    contactPhone: "7891•••••55",
    tags: ["sowing", "fertilizer placement"],
  },
  {
    id: "m-1005",
    category: "machinery",
    type: "Power Tiller",
    title: "Compact Power Tiller, 12 HP",
    description:
      "Lightweight power tiller suited to small plots and vegetable beds. Easy to transport between fields.",
    ownerName: "Lakshmi Bai",
    ownerVillageYears: 7,
    location: { village: "Sarwar", district: "Ajmer", state: "Rajasthan", distanceKm: 33.1 },
    price: 350,
    priceUnit: "per hour",
    availability: { status: "available", detail: "Free now" },
    condition: "1 year old, light use",
    icon: "🛠️",
    listedDaysAgo: 8,
    rating: 4.6,
    ratingCount: 15,
    contactPhone: "9057•••••23",
    tags: ["small plots", "vegetables"],
  },
  {
    id: "m-1006",
    category: "machinery",
    type: "Sprayer",
    title: "Tractor-Mounted Boom Sprayer",
    description:
      "12-metre boom sprayer for pesticide and herbicide application across large fields. Reduces labour cost significantly.",
    ownerName: "Harpreet Singh",
    ownerVillageYears: 16,
    location: { village: "Beawar", district: "Ajmer", state: "Rajasthan", distanceKm: 41.6 },
    price: 700,
    priceUnit: "per acre",
    availability: { status: "upcoming", detail: "Free after 23 Aug" },
    condition: "Well maintained",
    icon: "💦",
    listedDaysAgo: 3,
    rating: 4.2,
    ratingCount: 9,
    contactPhone: "9636•••••80",
    tags: ["spraying", "pest control"],
  },
  {
    id: "m-1007",
    category: "machinery",
    type: "Thresher",
    title: "Multi-Crop Thresher",
    description:
      "Handles wheat, gram and mustard threshing. Output up to 20 quintals per hour with a 2-person crew.",
    ownerName: "Om Prakash Meena",
    ownerVillageYears: 12,
    location: { village: "Kishangarh", district: "Ajmer", state: "Rajasthan", distanceKm: 3.4 },
    price: 550,
    priceUnit: "per hour",
    availability: { status: "available", detail: "Free now" },
    condition: "Serviced last month",
    icon: "🌽",
    listedDaysAgo: 6,
    rating: 4.5,
    ratingCount: 19,
    contactPhone: "8890•••••64",
    tags: ["threshing", "post-harvest"],
  },
  {
    id: "m-1008",
    category: "machinery",
    type: "Laser Land Leveller",
    title: "Laser Land Leveller, GPS-guided",
    description:
      "Precision land levelling to improve irrigation efficiency and uniform germination. Recommended before sowing.",
    ownerName: "Custom Hiring Centre, Nasirabad",
    ownerVillageYears: 5,
    location: { village: "Nasirabad", district: "Ajmer", state: "Rajasthan", distanceKm: 19.0 },
    price: 1100,
    priceUnit: "per acre",
    availability: { status: "available", detail: "Free now" },
    condition: "CHC-maintained, 2022 model",
    icon: "📐",
    listedDaysAgo: 10,
    rating: 4.8,
    ratingCount: 27,
    contactPhone: "9414•••••90",
    tags: ["land levelling", "irrigation efficiency"],
  },
  {
    id: "r-2001",
    category: "residue",
    type: "Wheat Straw (Bhusa)",
    title: "Dry Wheat Straw (Bhusa), Baled",
    description:
      "Clean, dry wheat straw baled and ready for pickup. Good for cattle fodder or mulching. Stored under cover.",
    ownerName: "Radhika Devi",
    ownerVillageYears: 10,
    location: { village: "Kishangarh", district: "Ajmer", state: "Rajasthan", distanceKm: 4.1 },
    price: 320,
    priceUnit: "per quintal",
    availability: { status: "available", detail: "50 quintals in stock" },
    quantity: "50 quintals",
    icon: "🌾",
    listedDaysAgo: 2,
    rating: 4.6,
    ratingCount: 14,
    contactPhone: "9928•••••33",
    tags: ["fodder", "baled", "cattle feed"],
  },
  {
    id: "r-2002",
    category: "residue",
    type: "Paddy Straw",
    title: "Paddy Straw for Mushroom / Fodder Use",
    description:
      "Loose paddy straw from this season's harvest, suitable for mushroom cultivation substrate or animal bedding.",
    ownerName: "Manjeet Kaur",
    ownerVillageYears: 8,
    location: { village: "Pushkar", district: "Ajmer", state: "Rajasthan", distanceKm: 12.9 },
    price: 180,
    priceUnit: "per quintal",
    availability: { status: "available", detail: "80 quintals in stock" },
    quantity: "80 quintals",
    icon: "🍄",
    listedDaysAgo: 3,
    rating: 4.3,
    ratingCount: 6,
    contactPhone: "9799•••••12",
    tags: ["mushroom substrate", "bedding"],
  },
  {
    id: "r-2003",
    category: "residue",
    type: "Cotton Stalks",
    title: "Cotton Stalks — Biomass / Fuel Grade",
    description:
      "Dried cotton stalks cleared post-harvest. Suitable for biomass briquetting or as boiler fuel feedstock.",
    ownerName: "Fateh Singh Rathore",
    ownerVillageYears: 15,
    location: { village: "Kekri", district: "Ajmer", state: "Rajasthan", distanceKm: 28.7 },
    price: 140,
    priceUnit: "per quintal",
    availability: { status: "upcoming", detail: "Ready from 25 Aug" },
    quantity: "120 quintals",
    icon: "🔥",
    listedDaysAgo: 1,
    rating: 4.1,
    ratingCount: 4,
    contactPhone: "9887•••••76",
    tags: ["biomass", "fuel grade", "briquetting"],
  },
  {
    id: "r-2004",
    category: "residue",
    type: "Mustard Husk",
    title: "Mustard Husk, Sundried",
    description:
      "Sundried mustard husk left after threshing. Good for composting and as low-cost cattle feed supplement.",
    ownerName: "Deep Chand Yadav",
    ownerVillageYears: 6,
    location: { village: "Sarwar", district: "Ajmer", state: "Rajasthan", distanceKm: 34.2 },
    price: 90,
    priceUnit: "per quintal",
    availability: { status: "available", detail: "30 quintals in stock" },
    quantity: "30 quintals",
    icon: "🌼",
    listedDaysAgo: 7,
    rating: 4.0,
    ratingCount: 3,
    contactPhone: "8107•••••29",
    tags: ["composting", "cattle feed"],
  },
  {
    id: "r-2005",
    category: "residue",
    type: "Sugarcane Trash",
    title: "Sugarcane Trash, Field-Ready",
    description:
      "Sugarcane leaf trash cleared after cane cutting. Can be collected directly from field or baled on request.",
    ownerName: "Balwant Singh",
    ownerVillageYears: 18,
    location: { village: "Beawar", district: "Ajmer", state: "Rajasthan", distanceKm: 42.3 },
    price: 110,
    priceUnit: "per quintal",
    availability: { status: "booked", detail: "Booked till 21 Aug" },
    quantity: "200 quintals",
    icon: "🎋",
    listedDaysAgo: 4,
    rating: 4.4,
    ratingCount: 11,
    contactPhone: "9414•••••62",
    tags: ["mulching", "field pickup"],
  },
  {
    id: "r-2006",
    category: "residue",
    type: "Maize Stover",
    title: "Maize Stover Bundles",
    description:
      "Maize stover collected and bundled after kharif harvest. Popular for silage-making and roof thatching.",
    ownerName: "Chhagan Lal Gurjar",
    ownerVillageYears: 13,
    location: { village: "Nasirabad", district: "Ajmer", state: "Rajasthan", distanceKm: 20.6 },
    price: 150,
    priceUnit: "per quintal",
    availability: { status: "available", detail: "60 quintals in stock" },
    quantity: "60 quintals",
    icon: "🌽",
    listedDaysAgo: 9,
    rating: 4.5,
    ratingCount: 7,
    contactPhone: "9694•••••48",
    tags: ["silage", "thatching"],
  },
];

export const demandPosts: DemandPost[] = [
  {
    id: "d-3001",
    category: "machinery",
    type: "Combine Harvester",
    title: "Need combine harvester for 8-acre wheat plot",
    requestedBy: "Mohan Lal Sharma",
    location: { village: "Bhinay", district: "Ajmer", state: "Rajasthan", distanceKm: 7.1 },
    quantityNeeded: "8 acres",
    neededBy: "Within next 5 days",
    budget: "₹2,000–2,500 / acre",
    urgency: "high",
    respondersCount: 3,
    postedDaysAgo: 1,
    notes: "Crop is ready, need harvesting before forecast rain next week.",
  },
  {
    id: "d-3002",
    category: "residue",
    type: "Wheat Straw (Bhusa)",
    title: "Buying bhusa in bulk for dairy unit",
    requestedBy: "Anand Dairy Cooperative",
    location: { village: "Kishangarh", district: "Ajmer", state: "Rajasthan", distanceKm: 3.9 },
    quantityNeeded: "200 quintals",
    neededBy: "By end of August",
    budget: "₹280–330 / quintal",
    urgency: "medium",
    respondersCount: 5,
    postedDaysAgo: 4,
    notes: "Looking for multiple sellers, can arrange own transport for pickup.",
  },
  {
    id: "d-3003",
    category: "machinery",
    type: "Laser Land Leveller",
    title: "Land levelling needed before rabi sowing",
    requestedBy: "Iqbal Ahmed",
    location: { village: "Kekri", district: "Ajmer", state: "Rajasthan", distanceKm: 29.4 },
    quantityNeeded: "5 acres",
    neededBy: "Next 2 weeks",
    budget: "₹1,000–1,200 / acre",
    urgency: "medium",
    respondersCount: 2,
    postedDaysAgo: 2,
    notes: "Field has uneven patches from last monsoon, needs proper levelling.",
  },
  {
    id: "d-3004",
    category: "residue",
    type: "Paddy Straw",
    title: "Mushroom unit needs fresh paddy straw",
    requestedBy: "Saraswati Mushroom Farm",
    location: { village: "Pushkar", district: "Ajmer", state: "Rajasthan", distanceKm: 13.5 },
    quantityNeeded: "100 quintals",
    neededBy: "Ongoing, monthly supply",
    budget: "₹160–200 / quintal",
    urgency: "low",
    respondersCount: 6,
    postedDaysAgo: 12,
    notes: "Prefer straw within 15 km to keep transport cost low. Long-term supply preferred.",
  },
  {
    id: "d-3005",
    category: "machinery",
    type: "Rotavator",
    title: "Rotavator needed for mustard field prep",
    requestedBy: "Kamla Devi",
    location: { village: "Sarwar", district: "Ajmer", state: "Rajasthan", distanceKm: 35.0 },
    quantityNeeded: "4 acres",
    neededBy: "This weekend",
    budget: "₹800–1,000 / acre",
    urgency: "high",
    respondersCount: 1,
    postedDaysAgo: 0,
    notes: "Sowing window closing soon, need it done before Sunday.",
  },
  {
    id: "d-3006",
    category: "residue",
    type: "Cotton Stalks",
    title: "Biomass plant sourcing cotton stalks",
    requestedBy: "Green Energy Biomass Unit",
    location: { village: "Beawar", district: "Ajmer", state: "Rajasthan", distanceKm: 40.8 },
    quantityNeeded: "500 quintals",
    neededBy: "Next 30 days",
    budget: "₹120–150 / quintal",
    urgency: "low",
    respondersCount: 4,
    postedDaysAgo: 6,
    notes: "Setting up a briquetting unit, need a steady supplier for the season.",
  },
];

export const dashboardStats = {
  myActiveListings: 3,
  myOpenRequests: 2,
  matchesFound: 11,
  estimatedSavings: 8400,
};

export const recentActivity = [
  {
    id: "a-1",
    message: "Suresh Patel accepted your request for the Mahindra 575 DI tractor",
    time: "2 hours ago",
    icon: "✅",
  },
  {
    id: "a-2",
    message: "New match found: Rotavator available 6.2 km from Kishangarh",
    time: "5 hours ago",
    icon: "🎯",
  },
  {
    id: "a-3",
    message: "Your wheat straw listing received 3 new enquiries",
    time: "Yesterday",
    icon: "📩",
  },
  {
    id: "a-4",
    message: "Price update: thresher rental in Kishangarh dropped to ₹550/hr",
    time: "2 days ago",
    icon: "💰",
  },
];
